### ISSUE TITLE
CalledProcessError of prepare_fish_for_sleuth()

### ISSUE THREAD

**Issue by csardas** [chapmanb/bcbio-nextgen#1900]
hi, 
I upgraded bcbio to 1.0.3a yesterday, RNAseq pipeline was broke in following processes:

```
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 46, in run_salmon_reads
    out_file = salmon_quant_reads(fq1, fq2, salmon_dir, gtf_file, fasta_file, data)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 84, in salmon_quant_reads
    sailfish.sleuthify_sailfish(tx_out_dir)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 87, in sleuthify_sailfish
    do.run(cmd.format(**locals()), "Converting Sailfish to Sleuth format.")
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/peterhouse/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /peterhouse/tools/bcbio/anaconda/bin/Rscript -e 'library("wasabi"); prepare_fish_for_sleuth(c("/peterhouse/data/RNAseq/analysis/ana01/SLY-S9/work/bcbiotx/tmpy94CCd/quant"))'
Loading required package: methods
Error in setnames(quant, c("target_id", "length", "tpm", "est_counts")) : 
  Can't assign 4 names to a 5 column data.table
Calls: prepare_fish_for_sleuth -> sapply -> lapply -> FUN -> setnames
Execution halted
' returned non-zero exit status 1

```

**Comment by mchimenti** [comment]
I also get this error after upgrading.  This is a problem with wasabi expecting the output of salmon to have 4 columns, but it is detecting an extra column in the 'quant.sf' salmon output for some reason?   

Traceback (most recent call last):
  File "/Shared/Bioinformatics/data/bcbio/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/Shared/Bioinformatics/data/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 252, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 113, in quantitate_expression_parallel
    samples = run_parallel("run_salmon_reads", samples)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 49, in run_salmon_reads
    return salmon.run_salmon_reads(*args)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 46, in run_salmon_reads
    out_file = salmon_quant_reads(fq1, fq2, salmon_dir, gtf_file, fasta_file, data)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 84, in salmon_quant_reads
    sailfish.sleuthify_sailfish(tx_out_dir)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 87, in sleuthify_sailfish
    do.run(cmd.format(**locals()), "Converting Sailfish to Sleuth format.")
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /Shared/Bioinformatics/data/bcbio/anaconda/bin/Rscript -e 'library("wasabi"); prepare_fish_for_sleuth(c("/Shared/Bioinformatics/data/mchiment/gaynor/rnaseq_project_20170411/bcbio_project/work/bcbiotx/tmp0Ih5oS/quant"))'
Loading required package: methods
Error in setnames(quant, c("target_id", "length", "tpm", "est_counts")) :
  Can't assign 4 names to a 5 column data.table
Calls: prepare_fish_for_sleuth -> sapply -> lapply -> FUN -> setnames
Execution halted
' returned non-zero exit status 1

**Comment by mchimenti** [comment]
The output of salmon has five columns; wasabi is expecting four.   I got around this before upgrading by simply using UNIX tools to remove a column from the outputs.  Now, b/c wasabi runs automatically I can't do that.  

Is there a way to prevent wasabi from running while a workaround or bug fix is being developed?  

Name	Length	EffectiveLength	TPM	NumReads
ENST00000456328	1657	1470.87	0	0
ENST00000515242	1653	1466.87	0	0
ENST00000518655	1483	1296.87	0	0
ENST00000450305	632	445.996	0	0

**Comment by roryk** [comment]
Hi everyone,

Oops, I missed this. Could you try updating the tools by adding `--tools` to the update?  I think this was an error due to the version of wasabi we were installing being stale; I pushed a new version of wasabi to bioconda a week ago that should fix this problem.

**Comment by rdocking** [comment]
Hi Rory - I tried updating today and am seeing the same error. I see this in `manifest/python-packages.yaml`: 

```
r-wasabi:
  name: r-wasabi
  version: 0.0.1
```

But see `wasabi_0.2` when I install the package locally.

**Comment by roryk** [comment]
Thanks, dang sorry that didn't fix it. The version number in python-packages.yaml is from the bioconda recipe, but it should still be installing wasabi 0.2. If you update wasabi manually from github by loading up the R that comes with bcbio and doing:

```
devtools::install_github("COMBINE-lab/wasabi")
```

does that end up fixing the error? I am pretty sure it is just wasabi is out of date and isn't getting updated.

**Comment by roryk** [comment]
The bioconda recipe should be reading 0.1 so it looks like maybe wasabi didn't get updated.

**Comment by roryk** [comment]
Thanks I fixed the bioconda recipe to be 0.2.

**Comment by rdocking** [comment]
Hi Rory - thanks for looking into this! Unfortunately, the updater still doesn't seem to be picking up the updated version for me. I tried forcing the wasabi part like so:

```
$> /projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/bin/conda install -y -c bioconda r-wasabi
......
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda:
#
r-wasabi                  0.0.1                  r3.2.2_0    bioconda
```

As you suggested, I've manually updated wasabi from within the bcbio conda environment - I'll check now whether that resolves the issue in the RNA-Seq pipeline:

```
> library(wasabi)
> session_info()
Session info -------------------------------------------------------------------
 setting  value
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_CA.UTF-8
 tz       <NA>
 date     2017-04-20

Packages -----------------------------------------------------------------------
 package    * version date       source
 chron        2.3-47  2015-06-24 CRAN (R 3.2.2)
 curl         0.9.4   2015-11-20 CRAN (R 3.2.2)
 data.table   1.9.6   2015-09-19 CRAN (R 3.2.2)
 devtools   * 1.12.0  2016-12-05 CRAN (R 3.2.2)
 digest       0.6.12  2017-01-27 CRAN (R 3.2.3)
 git2r        0.11.0  2015-08-12 CRAN (R 3.2.2)
 httr         1.0.0   2015-06-25 CRAN (R 3.2.2)
 knitr        1.15.1  2016-11-22 CRAN (R 3.2.3)
 magrittr     1.5     2014-11-22 CRAN (R 3.2.2)
 memoise      1.0.0   2016-01-29 CRAN (R 3.2.2)
 R6           2.2.0   2016-10-05 CRAN (R 3.2.3)
 rhdf5        2.14.0  2015-12-17 Bioconductor
 rjson        0.2.15  2014-11-03 CRAN (R 3.2.2)
 stringi      1.0-1   2015-10-22 CRAN (R 3.2.2)
 stringr      1.1.0   2016-08-19 CRAN (R 3.2.3)
 wasabi     * 0.2     2017-04-20 Github (COMBINE-lab/wasabi@f31c73e)
```

**Comment by mchimenti** [comment]
The update didn't pick up wasabi 0.2 for me either.  

How do I load the bcbio R and manually force an update?

**Comment by mchimenti** [comment]
Alternatively, how do I turn off wasabi from the RNA-Seq pipeline?  Is there a "tools_off" command that would allow that?

**Comment by rdocking** [comment]
A little more digging - when I search for wasabi version, conda seems to know that 0.2 is out there:

```
> ./conda search r-wasabi
Fetching package metadata .............
r-wasabi                     0.0.1                  r3.3.1_0  bioconda
                          *  0.0.1                  r3.2.2_0  bioconda
                             0.1                    r3.3.1_0  bioconda
                             0.2                    r3.3.1_0  bioconda
```

Perhaps this is related to #1898 ? When I try to specifically install 0.2, I see:

```
> ./conda install r-wasabi=0.2 -c bioconda
...
UnsatisfiableError: The following specifications were found to be in conflict:
  - r-ks
  - r-wasabi 0.2*
Use "conda info <package>" to see the dependencies for each package.
```

Looking at the info for the two packages, it looks like `r-ks` has a dependency on `r 3.2.2*` that prevents the update from happening.

**Comment by rdocking** [comment]
Using wasabi 0.2 installed via devtools seems to resolve the issue - my RNA-Seq analysis is past the Salmon step and on to DEXSeq now.

@mchimenti : to do this,  see @roryk's comment above. For me, this looked like:

1. Load up the version of R that was installed with bcbio. For me, this was: `bcbio/anaconda/bin/R`
2. Install 'devtools': `install.packages("devtools")`
3. Update wasabi from GitHub: `devtools::install_github("COMBINE-lab/wasabi")`

**Comment by roryk** [comment]
Thank you for figuring out what was going on. I'll disable the wasabi implementation for now until we can get the bioconda package situation straightened out.

**Comment by chapmanb** [comment]
Rory, Rod and Michael;
Sorry about the problems, I think the issue is R incompatbilities within our bioconda installs. We're using R 3.2.2 in bcbio now but the 0.2 version of wasabi built with R 3.3.1. bioconda is in a bit of a tricky place right now with some 3.2 and some 3.3 packages.

There is a 3.4 release due tomorrow and a bioconductor release that supports it next week. After that's out we need to take a look at re-updating all the R packages we use to be consistent across 3.4.

**Comment by rdocking** [comment]
Sounds good - thanks @roryk, @chapmanb !

**Comment by mchimenti** [comment]
Thanks for addressing this.  We are updating bcbio from development to get your 'disable wasabi' commit until this can be re-visited.

**Comment by naumenko-sa** [comment]
Sorry guys for complaining rather than fixing, but is the bug still here (bcbio-nextgen, 1.0.4)?
The method of @roryk - @rdocking works and allows to pass the quantification step.
It looks like the call
```
sailfish.sleuthify_sailfish(tx_out_dir)
```
is not disabled in the releases 1.0.4 and 1.0.5, and the RNA-seq pipeline crashes by default without manual wasabi update? Or is it something wrong with my environment?

Sergey

**Comment by roryk** [comment]
Thanks Sergey,

Dang, sorry about the onging problems. It should be pulling in wasabi 0.2 from bioconda with R 3.3.2. Which version of R and wasabi are installed? Have you done a `bcbio_nextgen.py upgrade --tools` to upgrade the versions of the installed tools?  I can disable it again but it seems like it should be working to me.

**Comment by naumenko-sa** [comment]
O, I see, I've upgraded the code and the data, but not the tools.
