### ISSUE TITLE
Errors when running tests

### ISSUE THREAD

**Issue by npbhavya** [chapmanb/bcbio-nextgen#1999]
Hi, 

I have downloaded and installed bcbio. Then I started running the tests to check, and it runs fine for the unit tests. For py.test tests/integration, I get the following errors;

========================================================================= test session starts ==========================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /N/soft/rhel6/bcbio/bcbio-nextgen-1.0.3, inifile:
plugins: cov-2.5.1, mock-1.6.0, marks-0.4
collected 0 items / 4 errors

================================================================================ ERRORS ================================================================================
_______________________________________________________ ERROR collecting tests/integration/test_S3_pipelines.py ________________________________________________________
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:215: in load_module
    py.builtin.exec_(co, mod.__dict__)
../../../bcbio-nextgen-1.0.3/tests/integration/test_S3_pipelines.py:9: in <module>
    @pytest.marks('S3', 'install_required')
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/pytest_marks-0.4-py2.7.egg/marks/marks.py:23: in __call__
    info = MarkInfo(mark, (), {})
E   TypeError: __init__() takes exactly 2 arguments (4 given)
______________________________________________________ ERROR collecting tests/integration/test_SequencingDump.py _______________________________________________________
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:215: in load_module
    py.builtin.exec_(co, mod.__dict__)
../../../bcbio-nextgen-1.0.3/tests/integration/test_SequencingDump.py:11: in <module>
    class TestSampleSheet(object):
../../../bcbio-nextgen-1.0.3/tests/integration/test_SequencingDump.py:20: in TestSampleSheet
    @pytest.marks('speed1')
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/pytest_marks-0.4-py2.7.egg/marks/marks.py:23: in __call__
    info = MarkInfo(mark, (), {})
E   TypeError: __init__() takes exactly 2 arguments (4 given)
____________________________________________________ ERROR collecting tests/integration/test_automated_analysis.py _____________________________________________________
/N/soft/rhel6/bcbio/bcbio-nextgen-1.0.3/tests/integration/test_automated_analysis.py:17: in <module>
    @pytest.mark.skip(reason='Multiplexing not supporting in latest versions')
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/pytest_marks-0.4-py2.7.egg/marks/marks.py:23: in __call__
    info = MarkInfo(mark, (), {})
E   TypeError: __init__() takes exactly 2 arguments (4 given)
_________________________________________________________ ERROR collecting tests/integration/test_pipeline.py __________________________________________________________
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:215: in load_module
    py.builtin.exec_(co, mod.__dict__)
../../../bcbio-nextgen-1.0.3/tests/integration/test_pipeline.py:17: in <module>
    class TestRunInfo(object):
../../../bcbio-nextgen-1.0.3/tests/integration/test_pipeline.py:19: in TestRunInfo
    @pytest.marks('speed1')
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/pytest_marks-0.4-py2.7.egg/marks/marks.py:23: in __call__
    info = MarkInfo(mark, (), {})
E   TypeError: __init__() takes exactly 2 arguments (4 given)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 4 error in 0.78 seconds ========================================================================

and the same with py.test tests/bcbio_vm

========================================================================= test session starts ==========================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /N/soft/rhel6/bcbio/bcbio-nextgen-1.0.3, inifile:
plugins: cov-2.5.1, mock-1.6.0, marks-0.4
collected 0 items / 1 errors

================================================================================ ERRORS ================================================================================
____________________________________________________________ ERROR collecting tests/bcbio_vm/test_docker.py ____________________________________________________________
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:215: in load_module
    py.builtin.exec_(co, mod.__dict__)
../../../bcbio-nextgen-1.0.3/tests/bcbio_vm/test_docker.py:10: in <module>
    @pytest.marks('docker')
/N/soft/rhel6/bcbio/1.0.3/anaconda/lib/python2.7/site-packages/pytest_marks-0.4-py2.7.egg/marks/marks.py:23: in __call__
    info = MarkInfo(mark, (), {})
E   TypeError: __init__() takes exactly 2 arguments (4 given)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 error in 0.20 seconds ========================================================================

I checked the PYTHONPATH to make sure it is running the python installed by anaconda and not whats already installed.

**Comment by chapmanb** [comment]
Thanks for trying out bcbio and apologies for the issue. There have been changes in the pytest test running infrastructure since the 1.0.3 which cause this issue -- specifically the pytest.marks module changed. We've fixed all these issues in the development version and are planning a new release for this weekend so the easiest path to avoiding the problem is to update to that:
```
bcbio_nextgen.py upgrade -u development
```
and then hopefully everything should pass cleanly. Please feel free to reopen if you run into any other problems at all. Thanks again for the report.

**Comment by npbhavya** [comment]
Hi,

I am still getting the following error when i run ./run_tests.sh. I did
upgrade the tools. Can you please help me with this.

Thank You,
Bhavya

__________________________________________________________________________
test_1_variantcall
__________________________________________________________________________

install_test_files = None, data_dir =
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated'

    @pytest.mark.speed1
    @pytest.mark.ensemble
    @pytest.mark.install_required
    def test_1_variantcall(install_test_files, data_dir):
        """Test variant calling with GATK pipeline.
        Requires GATK.
        """
        with make_workdir() as workdir:
            cl = ["bcbio_nextgen.py",
                  get_post_process_yaml(data_dir, workdir),
                  os.path.join(data_dir, os.pardir, "100326_FC6107FAAXX"),
                  os.path.join(data_dir, "run_info-variantcall.yaml")]
>           subprocess.check_call(cl)

/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/integration/test_automated_analysis.py:203:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _

popenargs = (['bcbio_nextgen.py',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml',
'/N/sof...ted/../100326_FC6107FAAXX',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated/run_info-variantcall.yaml'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_nextgen.py',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml',
'/N/soft...mated/../100326_FC6107FAAXX',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated/run_info-variantcall.yaml']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the Popen constructor.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           CalledProcessError: Command '['bcbio_nextgen.py',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated/../100326_FC6107FAAXX',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated/run_info-variantcall.yaml']'
returned non-zero exit status 1

/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/subprocess.py:186:
CalledProcessError
______________________________________________________________________________
test_5_bam
______________________________________________________________________________

install_test_files = None, data_dir =
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated'

    @pytest.mark.devel
    @pytest.mark.speed1
    def test_5_bam(install_test_files, data_dir):
        """Allow BAM files as input to pipeline.
        """
        with make_workdir() as workdir:
            cl = ["bcbio_nextgen.py",
                  get_post_process_yaml(data_dir, workdir),
                  os.path.join(data_dir, "run_info-bam.yaml")]
>           subprocess.check_call(cl)

/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/integration/test_automated_analysis.py:215:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _

popenargs = (['bcbio_nextgen.py',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated/run_info-bam.yaml'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_nextgen.py',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated/run_info-bam.yaml']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the Popen constructor.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           CalledProcessError: Command '['bcbio_nextgen.py',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml',
'/N/soft/rhel6/bcbio/1.0.4/bcbio-nextgen/tests/data/automated/run_info-bam.yaml']'
returned non-zero exit status 1

/N/soft/rhel6/bcbio/1.0.4/local/share/bcbio/anaconda/lib/python2.7/subprocess.py:186:
CalledProcessError
=========================================================================
57 tests deselected
==========================================================================
========================================================= 2 failed, 9
passed, 57 deselected in 128.23 seconds
==========================================================

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by chapmanb** [comment]
Bhavya;
Thanks for the detailed report and sorry about the continued problems. The snippets you posted tell me the tests that failed but the actual failures are higher up in the run output so I can't diagnose what went wrong. If you could post the full log for the test runs as a gist (https://gist.github.com/) I could dig through and hopefully identify the underlying issue. Thanks for the help debugging.

**Comment by npbhavya** [comment]
Hi,

I was just mailing you to let you know that i was able to figure out the
problems, once i moved to a node with a more memory and installed
GATK/Mutect, the ./run_tests.sh scripts ran without running into a error.

Thank You,

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by chapmanb** [comment]
Brilliant -- glad it works and thanks for following up. Hope all proceeds smoothly with bcbio from here.

**Comment by npbhavya** [comment]
Hi,

I need to install the genomes separately in another location from my bcbio
directory due to space limitations. Can you help me tweak
the -./bcbio_nextgen.py --genomes GRCh37 --aligners bwa --aligners bowtie2
command to i can install the genomes to another location.

Thank you,

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by chapmanb** [comment]
Bhavya;
I'd suggest using symlinks to handle this, which requires no changes at all to bcbio. You can move the large `/path/to/bcbio/genomes` directory to wherever you have more space and then provide a symlink to it from the expected location. Hope this helps.

**Comment by npbhavya** [comment]
Hi,

Thank You i was able to simlink the genomes.

I reran the ./run_tests.sh and now i am again running into errors. I have
attached the log file, can you please take a look at it and let me know
what is wrong.

Thank You,
Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by chapmanb** [comment]
Bhavya;
Sorry about the test issues. GitHub does not allow issue attachments so I didn't receive your log file to examine. Can you please post it as a gist (https://gist.github.com/) and link to it here? Happy to help with more details about the problem you're seeing. Thanks much.

**Comment by npbhavya** [comment]
Here you go, here is the link the gist
https://gist.github.com/npbhavya/cd628afb65f90a468e62f3d020cc6426 where i
have put up the error.

Thank You,
Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)

**Comment by chapmanb** [comment]
Bhavya;
Thanks much for the detailed log file. If you update to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
the tests should now pass cleanly. This was due to a recent change where we looked at the variantcaller to check what method to run and the test cases did not have variantcaller information -- as a result you got a KeyError and missed generating files needed for the tests. The latest code does things differently and appears to work cleanly for me. Please let us know if you run into anything else at all.

**Comment by npbhavya** [comment]
Hi,

Thank You, that worked.

-Bhavya

Bhavya Papudeshi
Bioinformatics Analyst
National Center for Genome Analysis Support (NCGAS)
